// Real hospitals & blood banks in Gujarat, collected from public directories (Sept 2026).
// Verify phone numbers/addresses before using in a live app.
module.exports = [
  { name: 'N. M. Patel Blood Bank Bilimora', address: 'Shroff Complex, Nr. Dr. Gupta Hospital, Bilimora, Navsari - 396445, Bilimora, Navsari', contactNumber: '02634 285913', type: 'blood_bank' },
  { name: 'Indian Red Cross Society Blood Centre, Navsari', address: 'B.K. Shah Red Cross Bhavan, Station Road, Navsari, Navsari', contactNumber: 'N/A', type: 'blood_bank' },
  { name: 'Lions Club Blood Bank', address: 'Shroff Complex, Sv Patel Road, Goharbaug, Bilimora - 396321, Bilimora, Navsari', contactNumber: 'N/A', type: 'blood_bank' },
  { name: 'Sushrusha Blood Centre', address: 'Udyog Nagar, Vejalpore, Sayaji Road, Navsari, Navsari', contactNumber: 'N/A', type: 'blood_bank' },
  { name: 'Red Cross Society', address: 'Railway Station Road, Vejalpore, Navsari - 396475, Navsari', contactNumber: 'N/A', type: 'blood_bank' },
  { name: 'Lions Medical Trust Blood Bank', address: 'Main Road, Sayaji Road, Navsari, Navsari', contactNumber: 'N/A', type: 'blood_bank' },
  { name: 'Gupta Hospital', address: 'Bilimora, Navsari - 396445, Bilimora, Navsari', contactNumber: 'N/A', type: 'hospital' },
  { name: 'Bardoli Civil Hospital', address: 'Station Road, Bardoli - 394601, Bardoli, Surat District', contactNumber: 'N/A', type: 'hospital' },
  { name: 'Kamrej Civil Hospital', address: 'Kamrej Char Rasta, NH 48, Kamrej - 394185, Kamrej, Surat', contactNumber: 'N/A', type: 'hospital' },
  { name: 'Kiran Multi Super Speciality Hospital & Research Centre', address: 'Vasta Devdi Road, Near Sumul Dairy, Surat - 395004, Surat', contactNumber: '0261-716 1111', type: 'hospital' },
  { name: 'Shalby Hospital', address: 'Nr Navyug College, Rander Road, Adajan, Surat - 395009, Surat', contactNumber: '0261-418 4444', type: 'hospital' },
  { name: 'Sunshine Global Hospitals', address: 'Beside Smart Bazar, Dumas, Piplod Road, Surat - 395007, Surat', contactNumber: '0261-717 1000', type: 'hospital' },
  { name: 'Universal Superspeciality Hospital', address: 'Behind New SMC Building, Civil Cross Road, Khatodara, Surat - 395001, Surat', contactNumber: 'N/A', type: 'hospital' },
  { name: 'Burhani Hospital', address: 'Kuvarsing Street, Khangad Sheri, Mahidharpura, Begampura, Surat - 395003, Surat', contactNumber: 'N/A', type: 'hospital' },
  { name: 'Anupam Hospital', address: '3rd Floor, Anupam Arcade, Canal Road, Parvat Patia, Surat - 395010, Surat', contactNumber: 'N/A', type: 'hospital' },
  { name: 'Unique Hospital', address: 'Opp. Kiran Motor, Civil Hospital Char Rasta, Sosyo Circle Lane, Surat - 395002, Surat', contactNumber: 'N/A', type: 'hospital' },
  { name: 'Love \'N\' Care Multispeciality Hospital', address: 'Rander Road, Tadwadi, Surat - 395005, Surat', contactNumber: 'N/A', type: 'hospital' },
  { name: 'Udhna Hospital', address: '18, Patel Colony, Behind Bank of Baroda, Udhna, Surat - 394210, Surat', contactNumber: 'N/A', type: 'hospital' },
  { name: 'SMIMER Hospital', address: 'Umarwada, Surat - 395010, Surat', contactNumber: '0261-266 2220', type: 'hospital' },
  { name: 'New Civil Hospital Surat', address: 'Muglisara, Surat - 395003, Surat', contactNumber: '0261-267 0800', type: 'hospital' },
  { name: 'Tapti Hospital', address: 'Lal Darwaja, Surat - 395003, Surat', contactNumber: '0261-232 2222', type: 'hospital' },
  { name: 'Adarsh Hospital', address: 'Amar Sapna Apartment, Adarsh Society, Nanpura, Surat, Surat', contactNumber: '0261-2232028', type: 'hospital' },
  { name: 'Adventist Wockhardt Heart Hospital', address: 'K Desai Marg, Opposite Chowpatty, Athwalines, Surat, Surat', contactNumber: '0261-6694444', type: 'hospital' },
  { name: 'Agrawal Hospital', address: '3rd Floor, Bhagwat Ashish Apartment, City Light, Surat, Surat', contactNumber: '0261-2228821', type: 'hospital' },
  { name: 'Apollo Hospital Surat', address: 'Anand Mahal Road, Girinagar Society, Muktanand Nagar, Surat, Surat', contactNumber: '18605007788', type: 'hospital' },
  { name: 'Apple Hospital', address: 'Udhna Darwaja, Ring Road, Surat, Surat', contactNumber: '0261-2310703', type: 'hospital' },
  { name: 'Blood Bank New Civil Hospital', address: 'Opposite ITI, Majura Gate, Surat, Surat', contactNumber: 'N/A', type: 'blood_bank' },
  { name: 'S.S.G. Hospital', address: 'Sardar Vallabhbhai Hospital Road, Vadodara - 390001, Vadodara', contactNumber: '0265-242 0711', type: 'hospital' },
  { name: 'Sir Sayajirao General Hospital', address: 'Sayajiganj, Vadodara - 390005, Vadodara', contactNumber: '0265-242 8888', type: 'hospital' },
  { name: 'Sayaji Hospital (Gandhi Nagar General Hospital)', address: 'Sayaji Hospital Road, Vadodara - 390001, Vadodara', contactNumber: '0265-241 2031', type: 'hospital' },
  { name: 'Bhailal Amin General Hospital (BAGH)', address: 'Gorwa Road, Vadodara - 390003, Vadodara', contactNumber: '0265-617 0011', type: 'hospital' },
  { name: 'Sunshine Global Hospital Vadodara', address: 'Old Padra Road, Vadodara - 390020, Vadodara', contactNumber: '0265-230 4000', type: 'hospital' },
  { name: 'Metro Hospital & Research Institute', address: 'Manjalpur, Vadodara - 390011, Vadodara', contactNumber: '0265-265 8888', type: 'hospital' },
  { name: 'Unity Multispeciality Hospital', address: 'Akota, Vadodara - 390020, Vadodara', contactNumber: '0265-662 2222', type: 'hospital' },
  { name: 'KIMS Hospital', address: 'Old Padra Road, Vadodara - 390015, Vadodara', contactNumber: '0265-235 3232', type: 'hospital' },
  { name: 'Sterling Hospital Vadodara', address: 'Vadodara, Vadodara', contactNumber: 'N/A', type: 'hospital' },
  { name: 'Sheth V.S. General Hospital', address: 'Ellisbridge, Ahmedabad, Ahmedabad', contactNumber: '079-26577621', type: 'hospital' },
  { name: 'Sheth Lallubhai Gordhandas Municipal General Hospital', address: 'Maninagar, Ahmedabad, Ahmedabad', contactNumber: '079-25461380', type: 'hospital' },
  { name: 'Smt. Shardaben Chimanlal Lalbhai Municipal General Hospital', address: 'Saraspur, Ahmedabad, Ahmedabad', contactNumber: '079-22924261', type: 'hospital' },
  { name: 'Sheth C.H. Nagari Municipal Eye Hospital', address: 'Near Gujarat College Char Rasta, Ellisbridge, Ahmedabad, Ahmedabad', contactNumber: '079-26460176', type: 'hospital' },
  { name: 'Apollo Hospitals City Center', address: 'Raj Nagar Club Road, Ellis Bridge, Ahmedabad - 380006, Ahmedabad', contactNumber: '079-66305800', type: 'hospital' },
  { name: 'CIMS Hospital', address: 'Sola Bridge, Science City Road, Sola, Ahmedabad - 380061, Ahmedabad', contactNumber: '079-66153315', type: 'hospital' },
  { name: 'Dr Jivraj Mehta Smarak Health Foundation', address: 'Bakeri Medical Research Centre, Vasna, Ahmedabad - 380007, Ahmedabad', contactNumber: '079-26639840', type: 'hospital' },
  { name: 'Ahmedabad Civil Hospital', address: 'Asarva, Ahmedabad, Ahmedabad', contactNumber: 'N/A', type: 'hospital' },
  { name: 'Shalby Hospitals', address: 'Opp. Karnavati Club, S.G. Road, Ahmedabad, Ahmedabad', contactNumber: 'N/A', type: 'hospital' },
  { name: 'Narayana Multispeciality Hospital', address: 'Chakudiya Mahadev, Rakhiyal Cross Road, Ahmedabad, Ahmedabad', contactNumber: 'N/A', type: 'hospital' },
  { name: 'Victoria Jubilee Hospital for Women', address: 'Ahmedabad, Ahmedabad', contactNumber: 'N/A', type: 'hospital' },
  { name: 'Sterling Hospitals Ahmedabad', address: 'Sterling Hospitals Road, Gurukul, Memnagar, Ahmedabad - 380052, Ahmedabad', contactNumber: 'N/A', type: 'hospital' },
  { name: 'SAL Hospital and Medical Institute', address: 'Opp. Doordarshan, Ahmedabad, Ahmedabad', contactNumber: '9825046801', type: 'hospital' }
];
